### ISSUE TITLE
Error in log when opening prefs

### ISSUE THREAD

**Issue by chwilliams42** [k0swe/forester#1120]
ERROR TypeError: Cannot set properties of undefined (setting 'disabled')
    at i.enableSaveButton (main.670fb76c19c20a76.js:1:1320767)
    at main.670fb76c19c20a76.js:1:1322229
    at rv (main.670fb76c19c20a76.js:1:2085971)
    at Object._ [as next] (main.670fb76c19c20a76.js:1:2086180)
    at _e.next (main.670fb76c19c20a76.js:1:2006532)
    at ze._next (main.670fb76c19c20a76.js:1:2006199)
    at ze.next (main.670fb76c19c20a76.js:1:2005885)
    at main.670fb76c19c20a76.js:1:2003756
    at b (main.670fb76c19c20a76.js:1:2019718)
    at Hk.next (main.670fb76c19c20a76.js:1:2003593)

**Comment by chwilliams42** [comment]
Note: when opening settings this is logged twice.

**Comment by xylo04** [comment]
I see it too when opening logbook settings. This is the unredacted stacktrace:

```
ERROR TypeError: Cannot set properties of undefined (setting 'disabled')
    at LogbookSettingsComponent.enableSaveButton (logbook-settings.component.ts:49:29)
    at LogbookSettingsComponent_Template_kel_station_detail_stationChange_7_listener (logbook-settings.component.html:8:26)
    at executeListenerWithErrorHandling (core.mjs:14935:16)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:14976:22)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at EventEmitter_.next (Subject.js:27:21)
```
